/**
 * Seeds default ingredient groups and plant foods.
 * Safe to re-run — uses onConflictDoNothing.
 * Called automatically by db:clean and on deploy (Dockerfile CMD).
 */
import { drizzle } from 'drizzle-orm/postgres-js';
import postgres from 'postgres';
import { ingredientGroups, plantFoods } from './db/schema.js';

const DATABASE_URL = process.env.DATABASE_URL;
if (!DATABASE_URL) throw new Error('DATABASE_URL is not set');

const client = postgres(DATABASE_URL);
const db = drizzle(client);

await db.insert(ingredientGroups).values([
	{ label: 'Karotte / Rüebli', matchKeys: ['rüebli', 'rüben', 'karotte'] },
	{ label: 'Zucchini',         matchKeys: ['zucchini', 'zucchetti'] },
	{ label: 'Peperoni',         matchKeys: ['peperoni', 'paprika'] },
	{ label: 'Randen',           matchKeys: ['randen', 'rote bete'] },
]).onConflictDoNothing();

await db.insert(plantFoods).values([
	{ matchKey: 'karotte',          label: 'Karotte' },
	{ matchKey: 'rüebli',           label: 'Rüebli' },
	{ matchKey: 'randen',           label: 'Randen' },
	{ matchKey: 'kartoffel',        label: 'Kartoffel' },
	{ matchKey: 'süsskartoffel',    label: 'Süsskartoffel' },
	{ matchKey: 'zwiebel',          label: 'Zwiebel' },
	{ matchKey: 'knoblauch',        label: 'Knoblauch' },
	{ matchKey: 'lauch',            label: 'Lauch' },
	{ matchKey: 'porre',            label: 'Porre' },
	{ matchKey: 'sellerie',         label: 'Sellerie' },
	{ matchKey: 'staudensellerie',  label: 'Staudensellerie' },
	{ matchKey: 'fenchel',          label: 'Fenchel' },
	{ matchKey: 'zucchini',         label: 'Zucchini' },
	{ matchKey: 'zucchetti',        label: 'Zucchetti' },
	{ matchKey: 'peperoni',         label: 'Peperoni' },
	{ matchKey: 'paprika',          label: 'Paprika' },
	{ matchKey: 'tomate',           label: 'Tomate' },
	{ matchKey: 'gurke',            label: 'Gurke' },
	{ matchKey: 'spinat',           label: 'Spinat' },
	{ matchKey: 'salat',            label: 'Salat' },
	{ matchKey: 'rucola',           label: 'Rucola' },
	{ matchKey: 'feldsalat',        label: 'Feldsalat' },
	{ matchKey: 'mangold',          label: 'Mangold' },
	{ matchKey: 'kohl',             label: 'Kohl' },
	{ matchKey: 'weisskohl',        label: 'Weisskohl' },
	{ matchKey: 'rotkohl',          label: 'Rotkohl' },
	{ matchKey: 'blumenkohl',       label: 'Blumenkohl' },
	{ matchKey: 'broccoli',         label: 'Broccoli' },
	{ matchKey: 'rosenkohl',        label: 'Rosenkohl' },
	{ matchKey: 'kohlrabi',         label: 'Kohlrabi' },
	{ matchKey: 'wirsing',          label: 'Wirsing' },
	{ matchKey: 'kürbis',           label: 'Kürbis' },
	{ matchKey: 'pastinake',        label: 'Pastinake' },
	{ matchKey: 'radieschen',       label: 'Radieschen' },
	{ matchKey: 'rettich',          label: 'Rettich' },
	{ matchKey: 'spargel',          label: 'Spargel' },
	{ matchKey: 'aubergine',        label: 'Aubergine' },
	{ matchKey: 'avocado',          label: 'Avocado' },
	{ matchKey: 'mais',             label: 'Mais' },
	{ matchKey: 'artischocke',      label: 'Artischocke' },
	{ matchKey: 'chicorée',         label: 'Chicorée' },
	{ matchKey: 'rhabarber',        label: 'Rhabarber' },
	{ matchKey: 'olive',            label: 'Olive' },
	{ matchKey: 'champignon',       label: 'Champignon' },
	{ matchKey: 'pilz',             label: 'Pilz' },
	{ matchKey: 'shiitake',         label: 'Shiitake' },
	{ matchKey: 'steinpilz',        label: 'Steinpilz' },
	{ matchKey: 'linse',            label: 'Linsen' },
	{ matchKey: 'kichererbse',      label: 'Kichererbsen' },
	{ matchKey: 'bohne',            label: 'Bohnen' },
	{ matchKey: 'erbse',            label: 'Erbsen' },
	{ matchKey: 'soja',             label: 'Soja' },
	{ matchKey: 'tofu',             label: 'Tofu' },
	{ matchKey: 'apfel',            label: 'Apfel' },
	{ matchKey: 'birne',            label: 'Birne' },
	{ matchKey: 'banane',           label: 'Banane' },
	{ matchKey: 'orange',           label: 'Orange' },
	{ matchKey: 'mandarine',        label: 'Mandarine' },
	{ matchKey: 'zitrone',          label: 'Zitrone' },
	{ matchKey: 'limette',          label: 'Limette' },
	{ matchKey: 'erdbeere',         label: 'Erdbeere' },
	{ matchKey: 'himbeere',         label: 'Himbeere' },
	{ matchKey: 'heidelbeere',      label: 'Heidelbeere' },
	{ matchKey: 'brombeere',        label: 'Brombeere' },
	{ matchKey: 'johannisbeere',    label: 'Johannisbeere' },
	{ matchKey: 'traube',           label: 'Traube' },
	{ matchKey: 'mango',            label: 'Mango' },
	{ matchKey: 'ananas',           label: 'Ananas' },
	{ matchKey: 'pfirsich',         label: 'Pfirsich' },
	{ matchKey: 'nektarine',        label: 'Nektarine' },
	{ matchKey: 'pflaume',          label: 'Pflaume' },
	{ matchKey: 'kirsche',          label: 'Kirsche' },
	{ matchKey: 'aprikose',         label: 'Aprikose' },
	{ matchKey: 'melone',           label: 'Melone' },
	{ matchKey: 'feige',            label: 'Feige' },
	{ matchKey: 'granatapfel',      label: 'Granatapfel' },
	{ matchKey: 'kiwi',             label: 'Kiwi' },
	{ matchKey: 'petersilie',       label: 'Petersilie' },
	{ matchKey: 'basilikum',        label: 'Basilikum' },
	{ matchKey: 'thymian',          label: 'Thymian' },
	{ matchKey: 'rosmarin',         label: 'Rosmarin' },
	{ matchKey: 'oregano',          label: 'Oregano' },
	{ matchKey: 'salbei',           label: 'Salbei' },
	{ matchKey: 'koriander',        label: 'Koriander' },
	{ matchKey: 'dill',             label: 'Dill' },
	{ matchKey: 'schnittlauch',     label: 'Schnittlauch' },
	{ matchKey: 'minze',            label: 'Minze' },
	{ matchKey: 'estragon',         label: 'Estragon' },
	{ matchKey: 'majoran',          label: 'Majoran' },
	{ matchKey: 'lorbeer',          label: 'Lorbeer' },
	{ matchKey: 'zitronengras',     label: 'Zitronengras' },
	{ matchKey: 'ingwer',           label: 'Ingwer' },
	{ matchKey: 'kurkuma',          label: 'Kurkuma' },
	{ matchKey: 'kreuzkümmel',      label: 'Kreuzkümmel' },
	{ matchKey: 'zimt',             label: 'Zimt' },
	{ matchKey: 'chili',            label: 'Chili' },
	{ matchKey: 'muskatnuss',       label: 'Muskatnuss' },
	{ matchKey: 'kardamom',         label: 'Kardamom' },
	{ matchKey: 'sternanis',        label: 'Sternanis' },
	{ matchKey: 'curry',            label: 'Curry' },
	{ matchKey: 'reis',             label: 'Reis' },
	{ matchKey: 'hafer',            label: 'Hafer' },
	{ matchKey: 'dinkel',           label: 'Dinkel' },
	{ matchKey: 'quinoa',           label: 'Quinoa' },
	{ matchKey: 'buchweizen',       label: 'Buchweizen' },
	{ matchKey: 'hirse',            label: 'Hirse' },
	{ matchKey: 'bulgur',           label: 'Bulgur' },
	{ matchKey: 'couscous',         label: 'Couscous' },
	{ matchKey: 'polenta',          label: 'Polenta' },
	{ matchKey: 'gerste',           label: 'Gerste' },
	{ matchKey: 'mandel',           label: 'Mandeln' },
	{ matchKey: 'walnuss',          label: 'Walnüsse' },
	{ matchKey: 'cashew',           label: 'Cashews' },
	{ matchKey: 'erdnuss',          label: 'Erdnüsse' },
	{ matchKey: 'haselnuss',        label: 'Haselnüsse' },
	{ matchKey: 'pistazie',         label: 'Pistazien' },
	{ matchKey: 'sesam',            label: 'Sesam' },
	{ matchKey: 'leinsamen',        label: 'Leinsamen' },
	{ matchKey: 'sonnenblumenkern', label: 'Sonnenblumenkerne' },
	{ matchKey: 'kürbiskern',       label: 'Kürbiskerne' },
	{ matchKey: 'pinienkern',       label: 'Pinienkerne' },
	{ matchKey: 'hanfsamen',        label: 'Hanfsamen' },
	{ matchKey: 'chiasamen',        label: 'Chiasamen' },
]).onConflictDoNothing();

console.log('Default data seeded.');
await client.end();
