CREATE TABLE IF NOT EXISTS "ingredient_groups" (
	"id" serial PRIMARY KEY NOT NULL,
	"label" text NOT NULL,
	"match_keys" text[] NOT NULL DEFAULT '{}'
);
--> statement-breakpoint
CREATE TABLE IF NOT EXISTS "plant_foods" (
	"id" serial PRIMARY KEY NOT NULL,
	"match_key" text NOT NULL,
	"label" text NOT NULL,
	CONSTRAINT "plant_foods_match_key_unique" UNIQUE("match_key")
);
--> statement-breakpoint
INSERT INTO "ingredient_groups" ("label", "match_keys") VALUES
	('Karotte / Rüebli', '{"rüebli","rüben","karotte"}'),
	('Zucchini',         '{"zucchini","zucchetti"}'),
	('Peperoni',         '{"peperoni","paprika"}'),
	('Randen',           '{"randen","rote bete"}');
--> statement-breakpoint
INSERT INTO "plant_foods" ("match_key", "label") VALUES
	('karotte',          'Karotte'),
	('rüebli',           'Rüebli'),
	('randen',           'Randen'),
	('kartoffel',        'Kartoffel'),
	('süsskartoffel',    'Süsskartoffel'),
	('zwiebel',          'Zwiebel'),
	('knoblauch',        'Knoblauch'),
	('lauch',            'Lauch'),
	('porre',            'Porre'),
	('sellerie',         'Sellerie'),
	('staudensellerie',  'Staudensellerie'),
	('fenchel',          'Fenchel'),
	('zucchini',         'Zucchini'),
	('zucchetti',        'Zucchetti'),
	('peperoni',         'Peperoni'),
	('paprika',          'Paprika'),
	('tomate',           'Tomate'),
	('gurke',            'Gurke'),
	('spinat',           'Spinat'),
	('salat',            'Salat'),
	('rucola',           'Rucola'),
	('feldsalat',        'Feldsalat'),
	('mangold',          'Mangold'),
	('kohl',             'Kohl'),
	('weisskohl',        'Weisskohl'),
	('rotkohl',          'Rotkohl'),
	('blumenkohl',       'Blumenkohl'),
	('broccoli',         'Broccoli'),
	('rosenkohl',        'Rosenkohl'),
	('kohlrabi',         'Kohlrabi'),
	('wirsing',          'Wirsing'),
	('kürbis',           'Kürbis'),
	('pastinake',        'Pastinake'),
	('radieschen',       'Radieschen'),
	('rettich',          'Rettich'),
	('spargel',          'Spargel'),
	('aubergine',        'Aubergine'),
	('avocado',          'Avocado'),
	('mais',             'Mais'),
	('artischocke',      'Artischocke'),
	('chicorée',         'Chicorée'),
	('rhabarber',        'Rhabarber'),
	('olive',            'Olive'),
	('champignon',       'Champignon'),
	('pilz',             'Pilz'),
	('shiitake',         'Shiitake'),
	('steinpilz',        'Steinpilz'),
	('linse',            'Linsen'),
	('kichererbse',      'Kichererbsen'),
	('bohne',            'Bohnen'),
	('erbse',            'Erbsen'),
	('soja',             'Soja'),
	('tofu',             'Tofu'),
	('apfel',            'Apfel'),
	('birne',            'Birne'),
	('banane',           'Banane'),
	('orange',           'Orange'),
	('mandarine',        'Mandarine'),
	('zitrone',          'Zitrone'),
	('limette',          'Limette'),
	('erdbeere',         'Erdbeere'),
	('himbeere',         'Himbeere'),
	('heidelbeere',      'Heidelbeere'),
	('brombeere',        'Brombeere'),
	('johannisbeere',    'Johannisbeere'),
	('traube',           'Traube'),
	('mango',            'Mango'),
	('ananas',           'Ananas'),
	('pfirsich',         'Pfirsich'),
	('nektarine',        'Nektarine'),
	('pflaume',          'Pflaume'),
	('kirsche',          'Kirsche'),
	('aprikose',         'Aprikose'),
	('melone',           'Melone'),
	('feige',            'Feige'),
	('granatapfel',      'Granatapfel'),
	('kiwi',             'Kiwi'),
	('petersilie',       'Petersilie'),
	('basilikum',        'Basilikum'),
	('thymian',          'Thymian'),
	('rosmarin',         'Rosmarin'),
	('oregano',          'Oregano'),
	('salbei',           'Salbei'),
	('koriander',        'Koriander'),
	('dill',             'Dill'),
	('schnittlauch',     'Schnittlauch'),
	('minze',            'Minze'),
	('estragon',         'Estragon'),
	('majoran',          'Majoran'),
	('lorbeer',          'Lorbeer'),
	('zitronengras',     'Zitronengras'),
	('ingwer',           'Ingwer'),
	('kurkuma',          'Kurkuma'),
	('kreuzkümmel',      'Kreuzkümmel'),
	('zimt',             'Zimt'),
	('chili',            'Chili'),
	('muskatnuss',       'Muskatnuss'),
	('kardamom',         'Kardamom'),
	('sternanis',        'Sternanis'),
	('curry',            'Curry'),
	('reis',             'Reis'),
	('hafer',            'Hafer'),
	('dinkel',           'Dinkel'),
	('quinoa',           'Quinoa'),
	('buchweizen',       'Buchweizen'),
	('hirse',            'Hirse'),
	('bulgur',           'Bulgur'),
	('couscous',         'Couscous'),
	('polenta',          'Polenta'),
	('gerste',           'Gerste'),
	('mandel',           'Mandeln'),
	('walnuss',          'Walnüsse'),
	('cashew',           'Cashews'),
	('erdnuss',          'Erdnüsse'),
	('haselnuss',        'Haselnüsse'),
	('pistazie',         'Pistazien'),
	('sesam',            'Sesam'),
	('leinsamen',        'Leinsamen'),
	('sonnenblumenkern', 'Sonnenblumenkerne'),
	('kürbiskern',       'Kürbiskerne'),
	('pinienkern',       'Pinienkerne'),
	('hanfsamen',        'Hanfsamen'),
	('chiasamen',        'Chiasamen')
ON CONFLICT DO NOTHING;
